version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: taskmanager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: taskmanager_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/task_manager?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: changeme
      NODE_ENV: production
    command: ["sh","-lc","pnpm prisma migrate deploy && pnpm start"]
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: taskmanager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:


